on:
  release:
    types: [created, published]
  push:
    branches: [ master ]
  workflow_dispatch:

name: Push to Godot Asset Library

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Push new release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to Godot Asset Library
        uses: wjt/godot-asset-lib-action@9cce3792b504bec69eb06b852b008d095e372f56
        with:
          username: ${{ secrets.GODOT_ASSET_LIBRARY_USERNAME }}
          password: ${{ secrets.GODOT_ASSET_STORE_PASSWORD }}
          assetId: 2212
          assetTemplate: .github/asset-template.json.hb