name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - run: cd $GITHUB_WORKSPACE

      - name: echo version
        run: |
          git remote update
          git tag -l

      - name: Tag and Publish
        run: git tag -l | grep v$(make version) || make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Name: ${{ github.event.release.name }}"
  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Name: ${{ github.event.release.name }}"
      